=== ayozetr/lnd-ejercicios-y-tareas/ut02-ejercicios/02-dtd/ejercicio02/filmoteca.dtd
<!ELEMENT filmoteca (pelicula+)>

<!ELEMENT pelicula (titulo, director, anio, duracion, genero, calificacion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>

<!ATTLIST duracion unidad (minutos) #IMPLIED> 

<!ELEMENT genero (#PCDATA)>
<!ELEMENT calificacion (#PCDATA)>

=== ayozetr/lnd-ejercicios-y-tareas/ut02-ejercicios/02-dtd/ejercicio02/filmoteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE filmoteca SYSTEM "filmoteca.dtd">
<filmoteca>
    <pelicula>
        <titulo>El Viaje Fantástico</titulo>
        <director>Pedro Gonzalez</director>
        <anio>2020</anio>
        <duracion>120</duracion>
        <genero>Ciencia Ficcion</genero>
        <calificacion>PG</calificacion>
    </pelicula>
    <pelicula>
        <titulo>La Venganza del Dragón</titulo>
        <director>Ana Martínez</director>
        <anio>2019</anio>
        <duracion>140</duracion>
        <genero>Acción</genero>
        <calificacion>R</calificacion>
    </pelicula>
    <pelicula>
        <titulo>La Aventura del Tiempo</titulo>
        <director>Jose Sánchez</director>
        <anio>2018</anio>
        <duracion>115</duracion>
        <genero>Aventura</genero>
        <calificacion>PG-13</calificacion>
    </pelicula>
    <pelicula>
        <titulo>Misterios del Universo</titulo>
        <director>Laura López</director>
        <anio>2021</anio>
        <duracion>130</duracion>
        <genero>Documental</genero>
        <calificacion>G</calificacion>
    </pelicula>
    <pelicula>
        <titulo>Un Viaje Extraordinario</titulo>
        <director>Marta Fernández</director>
        <anio>2017</anio>
        <duracion>100</duracion>
        <genero>Drama</genero>
        <calificacion>PG</calificacion>
    </pelicula>
</filmoteca>
